_BASE_: "../Base-BoxInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  FCOS:
    NUM_CLASSES: 20
  CONDINST:
    BOTTOM_PIXELS_REMOVED: 0
DATASETS:
  TRAIN: ("bbtp_voc_train",)
  TEST: ("bbtp_voc_val",)
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (15000,)
  MAX_ITER: 20000
  IMS_PER_BATCH: 8
INPUT:
  MIN_SIZE_TRAIN: (800,)
OUTPUT_DIR: "output/boxinst_MS_R_50_voc"
